### ISSUE TITLE
Email title has single quotes

### ISSUE THREAD

**Issue by rngadam** [dravedev/serment#6]
'J'ai signé le serment de Drave Dev'

should be 

J'ai signé le serment de Drave Développement

**Comment by rngadam** [comment]
@andiechu I can't find where this text is

**Comment by andiechu** [comment]
<img width="507" alt="截屏2021-03-22 下午12 07 22" src="https://user-images.githubusercontent.com/3121766/112021014-3d098c80-8b07-11eb-9ee9-e3886fb90084.png">
Fixed
